# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.21

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.21.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.21.1/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Volumes/Files/c/editor

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Volumes/Files/c/editor

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.21.1/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.21.1/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.21.1/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.21.1/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.21.1/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.21.1/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.21.1/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/local/Cellar/cmake/3.21.1/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.21.1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Volumes/Files/c/editor/CMakeFiles /Volumes/Files/c/editor//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Volumes/Files/c/editor/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sye

# Build rule for target.
sye: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sye
.PHONY : sye

# fast build rule for target.
sye/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/build
.PHONY : sye/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousCoverage.dir/build.make CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousTest.dir/build.make CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousBuild.dir/build.make CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousStart.dir/build.make CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalBuild.dir/build.make CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalCoverage.dir/build.make CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalSubmit.dir/build.make CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousUpdate.dir/build.make CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalUpdate.dir/build.make CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalStart.dir/build.make CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousSubmit.dir/build.make CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalTest.dir/build.make CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlySubmit.dir/build.make CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyMemCheck.dir/build.make CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalConfigure.dir/build.make CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyCoverage.dir/build.make CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyTest.dir/build.make CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousMemCheck.dir/build.make CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyBuild.dir/build.make CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyConfigure.dir/build.make CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyUpdate.dir/build.make CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyMemoryCheck.dir/build.make CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousConfigure.dir/build.make CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Nightly.dir/build.make CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyStart.dir/build.make CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalMemCheck.dir/build.make CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Continuous.dir/build.make CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Experimental.dir/build.make CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named test1

# Build rule for target.
test1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test1
.PHONY : test1

# fast build rule for target.
test1/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test1.dir/build.make tests/CMakeFiles/test1.dir/build
.PHONY : test1/fast

cmd/main.o: cmd/main.cpp.o
.PHONY : cmd/main.o

# target to build an object file
cmd/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/cmd/main.cpp.o
.PHONY : cmd/main.cpp.o

cmd/main.i: cmd/main.cpp.i
.PHONY : cmd/main.i

# target to preprocess a source file
cmd/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/cmd/main.cpp.i
.PHONY : cmd/main.cpp.i

cmd/main.s: cmd/main.cpp.s
.PHONY : cmd/main.s

# target to generate assembly for a file
cmd/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/cmd/main.cpp.s
.PHONY : cmd/main.cpp.s

internal/bufs/bufs.o: internal/bufs/bufs.cpp.o
.PHONY : internal/bufs/bufs.o

# target to build an object file
internal/bufs/bufs.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/bufs/bufs.cpp.o
.PHONY : internal/bufs/bufs.cpp.o

internal/bufs/bufs.i: internal/bufs/bufs.cpp.i
.PHONY : internal/bufs/bufs.i

# target to preprocess a source file
internal/bufs/bufs.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/bufs/bufs.cpp.i
.PHONY : internal/bufs/bufs.cpp.i

internal/bufs/bufs.s: internal/bufs/bufs.cpp.s
.PHONY : internal/bufs/bufs.s

# target to generate assembly for a file
internal/bufs/bufs.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/bufs/bufs.cpp.s
.PHONY : internal/bufs/bufs.cpp.s

internal/colors/colors.o: internal/colors/colors.cpp.o
.PHONY : internal/colors/colors.o

# target to build an object file
internal/colors/colors.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/colors/colors.cpp.o
.PHONY : internal/colors/colors.cpp.o

internal/colors/colors.i: internal/colors/colors.cpp.i
.PHONY : internal/colors/colors.i

# target to preprocess a source file
internal/colors/colors.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/colors/colors.cpp.i
.PHONY : internal/colors/colors.cpp.i

internal/colors/colors.s: internal/colors/colors.cpp.s
.PHONY : internal/colors/colors.s

# target to generate assembly for a file
internal/colors/colors.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/colors/colors.cpp.s
.PHONY : internal/colors/colors.cpp.s

internal/colors/command/command.o: internal/colors/command/command.cpp.o
.PHONY : internal/colors/command/command.o

# target to build an object file
internal/colors/command/command.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/colors/command/command.cpp.o
.PHONY : internal/colors/command/command.cpp.o

internal/colors/command/command.i: internal/colors/command/command.cpp.i
.PHONY : internal/colors/command/command.i

# target to preprocess a source file
internal/colors/command/command.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/colors/command/command.cpp.i
.PHONY : internal/colors/command/command.cpp.i

internal/colors/command/command.s: internal/colors/command/command.cpp.s
.PHONY : internal/colors/command/command.s

# target to generate assembly for a file
internal/colors/command/command.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/colors/command/command.cpp.s
.PHONY : internal/colors/command/command.cpp.s

internal/colors/effects/effects.o: internal/colors/effects/effects.cpp.o
.PHONY : internal/colors/effects/effects.o

# target to build an object file
internal/colors/effects/effects.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/colors/effects/effects.cpp.o
.PHONY : internal/colors/effects/effects.cpp.o

internal/colors/effects/effects.i: internal/colors/effects/effects.cpp.i
.PHONY : internal/colors/effects/effects.i

# target to preprocess a source file
internal/colors/effects/effects.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/colors/effects/effects.cpp.i
.PHONY : internal/colors/effects/effects.cpp.i

internal/colors/effects/effects.s: internal/colors/effects/effects.cpp.s
.PHONY : internal/colors/effects/effects.s

# target to generate assembly for a file
internal/colors/effects/effects.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/colors/effects/effects.cpp.s
.PHONY : internal/colors/effects/effects.cpp.s

internal/colors/font/font.o: internal/colors/font/font.cpp.o
.PHONY : internal/colors/font/font.o

# target to build an object file
internal/colors/font/font.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/colors/font/font.cpp.o
.PHONY : internal/colors/font/font.cpp.o

internal/colors/font/font.i: internal/colors/font/font.cpp.i
.PHONY : internal/colors/font/font.i

# target to preprocess a source file
internal/colors/font/font.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/colors/font/font.cpp.i
.PHONY : internal/colors/font/font.cpp.i

internal/colors/font/font.s: internal/colors/font/font.cpp.s
.PHONY : internal/colors/font/font.s

# target to generate assembly for a file
internal/colors/font/font.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/colors/font/font.cpp.s
.PHONY : internal/colors/font/font.cpp.s

internal/colors/insert/insert.o: internal/colors/insert/insert.cpp.o
.PHONY : internal/colors/insert/insert.o

# target to build an object file
internal/colors/insert/insert.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/colors/insert/insert.cpp.o
.PHONY : internal/colors/insert/insert.cpp.o

internal/colors/insert/insert.i: internal/colors/insert/insert.cpp.i
.PHONY : internal/colors/insert/insert.i

# target to preprocess a source file
internal/colors/insert/insert.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/colors/insert/insert.cpp.i
.PHONY : internal/colors/insert/insert.cpp.i

internal/colors/insert/insert.s: internal/colors/insert/insert.cpp.s
.PHONY : internal/colors/insert/insert.s

# target to generate assembly for a file
internal/colors/insert/insert.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/colors/insert/insert.cpp.s
.PHONY : internal/colors/insert/insert.cpp.s

internal/commands/applicator/applicator.o: internal/commands/applicator/applicator.cpp.o
.PHONY : internal/commands/applicator/applicator.o

# target to build an object file
internal/commands/applicator/applicator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/commands/applicator/applicator.cpp.o
.PHONY : internal/commands/applicator/applicator.cpp.o

internal/commands/applicator/applicator.i: internal/commands/applicator/applicator.cpp.i
.PHONY : internal/commands/applicator/applicator.i

# target to preprocess a source file
internal/commands/applicator/applicator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/commands/applicator/applicator.cpp.i
.PHONY : internal/commands/applicator/applicator.cpp.i

internal/commands/applicator/applicator.s: internal/commands/applicator/applicator.cpp.s
.PHONY : internal/commands/applicator/applicator.s

# target to generate assembly for a file
internal/commands/applicator/applicator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/commands/applicator/applicator.cpp.s
.PHONY : internal/commands/applicator/applicator.cpp.s

internal/commands/helper/helper.o: internal/commands/helper/helper.cpp.o
.PHONY : internal/commands/helper/helper.o

# target to build an object file
internal/commands/helper/helper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/commands/helper/helper.cpp.o
.PHONY : internal/commands/helper/helper.cpp.o

internal/commands/helper/helper.i: internal/commands/helper/helper.cpp.i
.PHONY : internal/commands/helper/helper.i

# target to preprocess a source file
internal/commands/helper/helper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/commands/helper/helper.cpp.i
.PHONY : internal/commands/helper/helper.cpp.i

internal/commands/helper/helper.s: internal/commands/helper/helper.cpp.s
.PHONY : internal/commands/helper/helper.s

# target to generate assembly for a file
internal/commands/helper/helper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/commands/helper/helper.cpp.s
.PHONY : internal/commands/helper/helper.cpp.s

internal/commands/search/search.o: internal/commands/search/search.cpp.o
.PHONY : internal/commands/search/search.o

# target to build an object file
internal/commands/search/search.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/commands/search/search.cpp.o
.PHONY : internal/commands/search/search.cpp.o

internal/commands/search/search.i: internal/commands/search/search.cpp.i
.PHONY : internal/commands/search/search.i

# target to preprocess a source file
internal/commands/search/search.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/commands/search/search.cpp.i
.PHONY : internal/commands/search/search.cpp.i

internal/commands/search/search.s: internal/commands/search/search.cpp.s
.PHONY : internal/commands/search/search.s

# target to generate assembly for a file
internal/commands/search/search.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/commands/search/search.cpp.s
.PHONY : internal/commands/search/search.cpp.s

internal/commands/w/w.o: internal/commands/w/w.cpp.o
.PHONY : internal/commands/w/w.o

# target to build an object file
internal/commands/w/w.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/commands/w/w.cpp.o
.PHONY : internal/commands/w/w.cpp.o

internal/commands/w/w.i: internal/commands/w/w.cpp.i
.PHONY : internal/commands/w/w.i

# target to preprocess a source file
internal/commands/w/w.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/commands/w/w.cpp.i
.PHONY : internal/commands/w/w.cpp.i

internal/commands/w/w.s: internal/commands/w/w.cpp.s
.PHONY : internal/commands/w/w.s

# target to generate assembly for a file
internal/commands/w/w.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/commands/w/w.cpp.s
.PHONY : internal/commands/w/w.cpp.s

internal/commands/z/z.o: internal/commands/z/z.cpp.o
.PHONY : internal/commands/z/z.o

# target to build an object file
internal/commands/z/z.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/commands/z/z.cpp.o
.PHONY : internal/commands/z/z.cpp.o

internal/commands/z/z.i: internal/commands/z/z.cpp.i
.PHONY : internal/commands/z/z.i

# target to preprocess a source file
internal/commands/z/z.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/commands/z/z.cpp.i
.PHONY : internal/commands/z/z.cpp.i

internal/commands/z/z.s: internal/commands/z/z.cpp.s
.PHONY : internal/commands/z/z.s

# target to generate assembly for a file
internal/commands/z/z.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/commands/z/z.cpp.s
.PHONY : internal/commands/z/z.cpp.s

internal/editor_status/editor_status.o: internal/editor_status/editor_status.cpp.o
.PHONY : internal/editor_status/editor_status.o

# target to build an object file
internal/editor_status/editor_status.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/editor_status/editor_status.cpp.o
.PHONY : internal/editor_status/editor_status.cpp.o

internal/editor_status/editor_status.i: internal/editor_status/editor_status.cpp.i
.PHONY : internal/editor_status/editor_status.i

# target to preprocess a source file
internal/editor_status/editor_status.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/editor_status/editor_status.cpp.i
.PHONY : internal/editor_status/editor_status.cpp.i

internal/editor_status/editor_status.s: internal/editor_status/editor_status.cpp.s
.PHONY : internal/editor_status/editor_status.s

# target to generate assembly for a file
internal/editor_status/editor_status.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/editor_status/editor_status.cpp.s
.PHONY : internal/editor_status/editor_status.cpp.s

internal/files/configs/helper/helper.o: internal/files/configs/helper/helper.cpp.o
.PHONY : internal/files/configs/helper/helper.o

# target to build an object file
internal/files/configs/helper/helper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/files/configs/helper/helper.cpp.o
.PHONY : internal/files/configs/helper/helper.cpp.o

internal/files/configs/helper/helper.i: internal/files/configs/helper/helper.cpp.i
.PHONY : internal/files/configs/helper/helper.i

# target to preprocess a source file
internal/files/configs/helper/helper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/files/configs/helper/helper.cpp.i
.PHONY : internal/files/configs/helper/helper.cpp.i

internal/files/configs/helper/helper.s: internal/files/configs/helper/helper.cpp.s
.PHONY : internal/files/configs/helper/helper.s

# target to generate assembly for a file
internal/files/configs/helper/helper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/files/configs/helper/helper.cpp.s
.PHONY : internal/files/configs/helper/helper.cpp.s

internal/files/configs/syntax_config/syntax_config.o: internal/files/configs/syntax_config/syntax_config.cpp.o
.PHONY : internal/files/configs/syntax_config/syntax_config.o

# target to build an object file
internal/files/configs/syntax_config/syntax_config.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/files/configs/syntax_config/syntax_config.cpp.o
.PHONY : internal/files/configs/syntax_config/syntax_config.cpp.o

internal/files/configs/syntax_config/syntax_config.i: internal/files/configs/syntax_config/syntax_config.cpp.i
.PHONY : internal/files/configs/syntax_config/syntax_config.i

# target to preprocess a source file
internal/files/configs/syntax_config/syntax_config.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/files/configs/syntax_config/syntax_config.cpp.i
.PHONY : internal/files/configs/syntax_config/syntax_config.cpp.i

internal/files/configs/syntax_config/syntax_config.s: internal/files/configs/syntax_config/syntax_config.cpp.s
.PHONY : internal/files/configs/syntax_config/syntax_config.s

# target to generate assembly for a file
internal/files/configs/syntax_config/syntax_config.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/files/configs/syntax_config/syntax_config.cpp.s
.PHONY : internal/files/configs/syntax_config/syntax_config.cpp.s

internal/files/configs/theme_config/theme_config.o: internal/files/configs/theme_config/theme_config.cpp.o
.PHONY : internal/files/configs/theme_config/theme_config.o

# target to build an object file
internal/files/configs/theme_config/theme_config.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/files/configs/theme_config/theme_config.cpp.o
.PHONY : internal/files/configs/theme_config/theme_config.cpp.o

internal/files/configs/theme_config/theme_config.i: internal/files/configs/theme_config/theme_config.cpp.i
.PHONY : internal/files/configs/theme_config/theme_config.i

# target to preprocess a source file
internal/files/configs/theme_config/theme_config.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/files/configs/theme_config/theme_config.cpp.i
.PHONY : internal/files/configs/theme_config/theme_config.cpp.i

internal/files/configs/theme_config/theme_config.s: internal/files/configs/theme_config/theme_config.cpp.s
.PHONY : internal/files/configs/theme_config/theme_config.s

# target to generate assembly for a file
internal/files/configs/theme_config/theme_config.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/files/configs/theme_config/theme_config.cpp.s
.PHONY : internal/files/configs/theme_config/theme_config.cpp.s

internal/files/exec/exec.o: internal/files/exec/exec.cpp.o
.PHONY : internal/files/exec/exec.o

# target to build an object file
internal/files/exec/exec.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/files/exec/exec.cpp.o
.PHONY : internal/files/exec/exec.cpp.o

internal/files/exec/exec.i: internal/files/exec/exec.cpp.i
.PHONY : internal/files/exec/exec.i

# target to preprocess a source file
internal/files/exec/exec.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/files/exec/exec.cpp.i
.PHONY : internal/files/exec/exec.cpp.i

internal/files/exec/exec.s: internal/files/exec/exec.cpp.s
.PHONY : internal/files/exec/exec.s

# target to generate assembly for a file
internal/files/exec/exec.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/files/exec/exec.cpp.s
.PHONY : internal/files/exec/exec.cpp.s

internal/files/helper/helper.o: internal/files/helper/helper.cpp.o
.PHONY : internal/files/helper/helper.o

# target to build an object file
internal/files/helper/helper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/files/helper/helper.cpp.o
.PHONY : internal/files/helper/helper.cpp.o

internal/files/helper/helper.i: internal/files/helper/helper.cpp.i
.PHONY : internal/files/helper/helper.i

# target to preprocess a source file
internal/files/helper/helper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/files/helper/helper.cpp.i
.PHONY : internal/files/helper/helper.cpp.i

internal/files/helper/helper.s: internal/files/helper/helper.cpp.s
.PHONY : internal/files/helper/helper.s

# target to generate assembly for a file
internal/files/helper/helper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/files/helper/helper.cpp.s
.PHONY : internal/files/helper/helper.cpp.s

internal/files/log/log.o: internal/files/log/log.cpp.o
.PHONY : internal/files/log/log.o

# target to build an object file
internal/files/log/log.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/files/log/log.cpp.o
.PHONY : internal/files/log/log.cpp.o

internal/files/log/log.i: internal/files/log/log.cpp.i
.PHONY : internal/files/log/log.i

# target to preprocess a source file
internal/files/log/log.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/files/log/log.cpp.i
.PHONY : internal/files/log/log.cpp.i

internal/files/log/log.s: internal/files/log/log.cpp.s
.PHONY : internal/files/log/log.s

# target to generate assembly for a file
internal/files/log/log.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/files/log/log.cpp.s
.PHONY : internal/files/log/log.cpp.s

internal/helper/helper.o: internal/helper/helper.cpp.o
.PHONY : internal/helper/helper.o

# target to build an object file
internal/helper/helper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/helper/helper.cpp.o
.PHONY : internal/helper/helper.cpp.o

internal/helper/helper.i: internal/helper/helper.cpp.i
.PHONY : internal/helper/helper.i

# target to preprocess a source file
internal/helper/helper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/helper/helper.cpp.i
.PHONY : internal/helper/helper.cpp.i

internal/helper/helper.s: internal/helper/helper.cpp.s
.PHONY : internal/helper/helper.s

# target to generate assembly for a file
internal/helper/helper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/helper/helper.cpp.s
.PHONY : internal/helper/helper.cpp.s

internal/highlighter/highlighter.o: internal/highlighter/highlighter.cpp.o
.PHONY : internal/highlighter/highlighter.o

# target to build an object file
internal/highlighter/highlighter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/highlighter/highlighter.cpp.o
.PHONY : internal/highlighter/highlighter.cpp.o

internal/highlighter/highlighter.i: internal/highlighter/highlighter.cpp.i
.PHONY : internal/highlighter/highlighter.i

# target to preprocess a source file
internal/highlighter/highlighter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/highlighter/highlighter.cpp.i
.PHONY : internal/highlighter/highlighter.cpp.i

internal/highlighter/highlighter.s: internal/highlighter/highlighter.cpp.s
.PHONY : internal/highlighter/highlighter.s

# target to generate assembly for a file
internal/highlighter/highlighter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/highlighter/highlighter.cpp.s
.PHONY : internal/highlighter/highlighter.cpp.s

internal/history/history.o: internal/history/history.cpp.o
.PHONY : internal/history/history.o

# target to build an object file
internal/history/history.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/history/history.cpp.o
.PHONY : internal/history/history.cpp.o

internal/history/history.i: internal/history/history.cpp.i
.PHONY : internal/history/history.i

# target to preprocess a source file
internal/history/history.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/history/history.cpp.i
.PHONY : internal/history/history.cpp.i

internal/history/history.s: internal/history/history.cpp.s
.PHONY : internal/history/history.s

# target to generate assembly for a file
internal/history/history.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/history/history.cpp.s
.PHONY : internal/history/history.cpp.s

internal/keys/keys.o: internal/keys/keys.cpp.o
.PHONY : internal/keys/keys.o

# target to build an object file
internal/keys/keys.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/keys/keys.cpp.o
.PHONY : internal/keys/keys.cpp.o

internal/keys/keys.i: internal/keys/keys.cpp.i
.PHONY : internal/keys/keys.i

# target to preprocess a source file
internal/keys/keys.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/keys/keys.cpp.i
.PHONY : internal/keys/keys.cpp.i

internal/keys/keys.s: internal/keys/keys.cpp.s
.PHONY : internal/keys/keys.s

# target to generate assembly for a file
internal/keys/keys.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/keys/keys.cpp.s
.PHONY : internal/keys/keys.cpp.s

internal/loop/helper/helper.o: internal/loop/helper/helper.cpp.o
.PHONY : internal/loop/helper/helper.o

# target to build an object file
internal/loop/helper/helper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/loop/helper/helper.cpp.o
.PHONY : internal/loop/helper/helper.cpp.o

internal/loop/helper/helper.i: internal/loop/helper/helper.cpp.i
.PHONY : internal/loop/helper/helper.i

# target to preprocess a source file
internal/loop/helper/helper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/loop/helper/helper.cpp.i
.PHONY : internal/loop/helper/helper.cpp.i

internal/loop/helper/helper.s: internal/loop/helper/helper.cpp.s
.PHONY : internal/loop/helper/helper.s

# target to generate assembly for a file
internal/loop/helper/helper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/loop/helper/helper.cpp.s
.PHONY : internal/loop/helper/helper.cpp.s

internal/loop/initialisers/initialisers.o: internal/loop/initialisers/initialisers.cpp.o
.PHONY : internal/loop/initialisers/initialisers.o

# target to build an object file
internal/loop/initialisers/initialisers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/loop/initialisers/initialisers.cpp.o
.PHONY : internal/loop/initialisers/initialisers.cpp.o

internal/loop/initialisers/initialisers.i: internal/loop/initialisers/initialisers.cpp.i
.PHONY : internal/loop/initialisers/initialisers.i

# target to preprocess a source file
internal/loop/initialisers/initialisers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/loop/initialisers/initialisers.cpp.i
.PHONY : internal/loop/initialisers/initialisers.cpp.i

internal/loop/initialisers/initialisers.s: internal/loop/initialisers/initialisers.cpp.s
.PHONY : internal/loop/initialisers/initialisers.s

# target to generate assembly for a file
internal/loop/initialisers/initialisers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/loop/initialisers/initialisers.cpp.s
.PHONY : internal/loop/initialisers/initialisers.cpp.s

internal/loop/loop.o: internal/loop/loop.cpp.o
.PHONY : internal/loop/loop.o

# target to build an object file
internal/loop/loop.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/loop/loop.cpp.o
.PHONY : internal/loop/loop.cpp.o

internal/loop/loop.i: internal/loop/loop.cpp.i
.PHONY : internal/loop/loop.i

# target to preprocess a source file
internal/loop/loop.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/loop/loop.cpp.i
.PHONY : internal/loop/loop.cpp.i

internal/loop/loop.s: internal/loop/loop.cpp.s
.PHONY : internal/loop/loop.s

# target to generate assembly for a file
internal/loop/loop.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/loop/loop.cpp.s
.PHONY : internal/loop/loop.cpp.s

internal/loop/processors/processors.o: internal/loop/processors/processors.cpp.o
.PHONY : internal/loop/processors/processors.o

# target to build an object file
internal/loop/processors/processors.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/loop/processors/processors.cpp.o
.PHONY : internal/loop/processors/processors.cpp.o

internal/loop/processors/processors.i: internal/loop/processors/processors.cpp.i
.PHONY : internal/loop/processors/processors.i

# target to preprocess a source file
internal/loop/processors/processors.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/loop/processors/processors.cpp.i
.PHONY : internal/loop/processors/processors.cpp.i

internal/loop/processors/processors.s: internal/loop/processors/processors.cpp.s
.PHONY : internal/loop/processors/processors.s

# target to generate assembly for a file
internal/loop/processors/processors.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/loop/processors/processors.cpp.s
.PHONY : internal/loop/processors/processors.cpp.s

internal/margin/margin.o: internal/margin/margin.cpp.o
.PHONY : internal/margin/margin.o

# target to build an object file
internal/margin/margin.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/margin/margin.cpp.o
.PHONY : internal/margin/margin.cpp.o

internal/margin/margin.i: internal/margin/margin.cpp.i
.PHONY : internal/margin/margin.i

# target to preprocess a source file
internal/margin/margin.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/margin/margin.cpp.i
.PHONY : internal/margin/margin.cpp.i

internal/margin/margin.s: internal/margin/margin.cpp.s
.PHONY : internal/margin/margin.s

# target to generate assembly for a file
internal/margin/margin.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/margin/margin.cpp.s
.PHONY : internal/margin/margin.cpp.s

internal/position/position.o: internal/position/position.cpp.o
.PHONY : internal/position/position.o

# target to build an object file
internal/position/position.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/position/position.cpp.o
.PHONY : internal/position/position.cpp.o

internal/position/position.i: internal/position/position.cpp.i
.PHONY : internal/position/position.i

# target to preprocess a source file
internal/position/position.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/position/position.cpp.i
.PHONY : internal/position/position.cpp.i

internal/position/position.s: internal/position/position.cpp.s
.PHONY : internal/position/position.s

# target to generate assembly for a file
internal/position/position.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/position/position.cpp.s
.PHONY : internal/position/position.cpp.s

internal/render/render.o: internal/render/render.cpp.o
.PHONY : internal/render/render.o

# target to build an object file
internal/render/render.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/render/render.cpp.o
.PHONY : internal/render/render.cpp.o

internal/render/render.i: internal/render/render.cpp.i
.PHONY : internal/render/render.i

# target to preprocess a source file
internal/render/render.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/render/render.cpp.i
.PHONY : internal/render/render.cpp.i

internal/render/render.s: internal/render/render.cpp.s
.PHONY : internal/render/render.s

# target to generate assembly for a file
internal/render/render.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/render/render.cpp.s
.PHONY : internal/render/render.cpp.s

internal/states/command/command.o: internal/states/command/command.cpp.o
.PHONY : internal/states/command/command.o

# target to build an object file
internal/states/command/command.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/states/command/command.cpp.o
.PHONY : internal/states/command/command.cpp.o

internal/states/command/command.i: internal/states/command/command.cpp.i
.PHONY : internal/states/command/command.i

# target to preprocess a source file
internal/states/command/command.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/states/command/command.cpp.i
.PHONY : internal/states/command/command.cpp.i

internal/states/command/command.s: internal/states/command/command.cpp.s
.PHONY : internal/states/command/command.s

# target to generate assembly for a file
internal/states/command/command.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/states/command/command.cpp.s
.PHONY : internal/states/command/command.cpp.s

internal/states/common/common.o: internal/states/common/common.cpp.o
.PHONY : internal/states/common/common.o

# target to build an object file
internal/states/common/common.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/states/common/common.cpp.o
.PHONY : internal/states/common/common.cpp.o

internal/states/common/common.i: internal/states/common/common.cpp.i
.PHONY : internal/states/common/common.i

# target to preprocess a source file
internal/states/common/common.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/states/common/common.cpp.i
.PHONY : internal/states/common/common.cpp.i

internal/states/common/common.s: internal/states/common/common.cpp.s
.PHONY : internal/states/common/common.s

# target to generate assembly for a file
internal/states/common/common.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/states/common/common.cpp.s
.PHONY : internal/states/common/common.cpp.s

internal/states/common/helper/helper.o: internal/states/common/helper/helper.cpp.o
.PHONY : internal/states/common/helper/helper.o

# target to build an object file
internal/states/common/helper/helper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/states/common/helper/helper.cpp.o
.PHONY : internal/states/common/helper/helper.cpp.o

internal/states/common/helper/helper.i: internal/states/common/helper/helper.cpp.i
.PHONY : internal/states/common/helper/helper.i

# target to preprocess a source file
internal/states/common/helper/helper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/states/common/helper/helper.cpp.i
.PHONY : internal/states/common/helper/helper.cpp.i

internal/states/common/helper/helper.s: internal/states/common/helper/helper.cpp.s
.PHONY : internal/states/common/helper/helper.s

# target to generate assembly for a file
internal/states/common/helper/helper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/states/common/helper/helper.cpp.s
.PHONY : internal/states/common/helper/helper.cpp.s

internal/states/insert/insert.o: internal/states/insert/insert.cpp.o
.PHONY : internal/states/insert/insert.o

# target to build an object file
internal/states/insert/insert.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/states/insert/insert.cpp.o
.PHONY : internal/states/insert/insert.cpp.o

internal/states/insert/insert.i: internal/states/insert/insert.cpp.i
.PHONY : internal/states/insert/insert.i

# target to preprocess a source file
internal/states/insert/insert.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/states/insert/insert.cpp.i
.PHONY : internal/states/insert/insert.cpp.i

internal/states/insert/insert.s: internal/states/insert/insert.cpp.s
.PHONY : internal/states/insert/insert.s

# target to generate assembly for a file
internal/states/insert/insert.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/states/insert/insert.cpp.s
.PHONY : internal/states/insert/insert.cpp.s

internal/states/search/search.o: internal/states/search/search.cpp.o
.PHONY : internal/states/search/search.o

# target to build an object file
internal/states/search/search.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/states/search/search.cpp.o
.PHONY : internal/states/search/search.cpp.o

internal/states/search/search.i: internal/states/search/search.cpp.i
.PHONY : internal/states/search/search.i

# target to preprocess a source file
internal/states/search/search.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/states/search/search.cpp.i
.PHONY : internal/states/search/search.cpp.i

internal/states/search/search.s: internal/states/search/search.cpp.s
.PHONY : internal/states/search/search.s

# target to generate assembly for a file
internal/states/search/search.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/states/search/search.cpp.s
.PHONY : internal/states/search/search.cpp.s

internal/term_flags/term_flags.o: internal/term_flags/term_flags.cpp.o
.PHONY : internal/term_flags/term_flags.o

# target to build an object file
internal/term_flags/term_flags.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/term_flags/term_flags.cpp.o
.PHONY : internal/term_flags/term_flags.cpp.o

internal/term_flags/term_flags.i: internal/term_flags/term_flags.cpp.i
.PHONY : internal/term_flags/term_flags.i

# target to preprocess a source file
internal/term_flags/term_flags.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/term_flags/term_flags.cpp.i
.PHONY : internal/term_flags/term_flags.cpp.i

internal/term_flags/term_flags.s: internal/term_flags/term_flags.cpp.s
.PHONY : internal/term_flags/term_flags.s

# target to generate assembly for a file
internal/term_flags/term_flags.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sye.dir/build.make CMakeFiles/sye.dir/internal/term_flags/term_flags.cpp.s
.PHONY : internal/term_flags/term_flags.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... Continuous"
	@echo "... ContinuousBuild"
	@echo "... ContinuousConfigure"
	@echo "... ContinuousCoverage"
	@echo "... ContinuousMemCheck"
	@echo "... ContinuousStart"
	@echo "... ContinuousSubmit"
	@echo "... ContinuousTest"
	@echo "... ContinuousUpdate"
	@echo "... Experimental"
	@echo "... ExperimentalBuild"
	@echo "... ExperimentalConfigure"
	@echo "... ExperimentalCoverage"
	@echo "... ExperimentalMemCheck"
	@echo "... ExperimentalStart"
	@echo "... ExperimentalSubmit"
	@echo "... ExperimentalTest"
	@echo "... ExperimentalUpdate"
	@echo "... Nightly"
	@echo "... NightlyBuild"
	@echo "... NightlyConfigure"
	@echo "... NightlyCoverage"
	@echo "... NightlyMemCheck"
	@echo "... NightlyMemoryCheck"
	@echo "... NightlyStart"
	@echo "... NightlySubmit"
	@echo "... NightlyTest"
	@echo "... NightlyUpdate"
	@echo "... sye"
	@echo "... test1"
	@echo "... cmd/main.o"
	@echo "... cmd/main.i"
	@echo "... cmd/main.s"
	@echo "... internal/bufs/bufs.o"
	@echo "... internal/bufs/bufs.i"
	@echo "... internal/bufs/bufs.s"
	@echo "... internal/colors/colors.o"
	@echo "... internal/colors/colors.i"
	@echo "... internal/colors/colors.s"
	@echo "... internal/colors/command/command.o"
	@echo "... internal/colors/command/command.i"
	@echo "... internal/colors/command/command.s"
	@echo "... internal/colors/effects/effects.o"
	@echo "... internal/colors/effects/effects.i"
	@echo "... internal/colors/effects/effects.s"
	@echo "... internal/colors/font/font.o"
	@echo "... internal/colors/font/font.i"
	@echo "... internal/colors/font/font.s"
	@echo "... internal/colors/insert/insert.o"
	@echo "... internal/colors/insert/insert.i"
	@echo "... internal/colors/insert/insert.s"
	@echo "... internal/commands/applicator/applicator.o"
	@echo "... internal/commands/applicator/applicator.i"
	@echo "... internal/commands/applicator/applicator.s"
	@echo "... internal/commands/helper/helper.o"
	@echo "... internal/commands/helper/helper.i"
	@echo "... internal/commands/helper/helper.s"
	@echo "... internal/commands/search/search.o"
	@echo "... internal/commands/search/search.i"
	@echo "... internal/commands/search/search.s"
	@echo "... internal/commands/w/w.o"
	@echo "... internal/commands/w/w.i"
	@echo "... internal/commands/w/w.s"
	@echo "... internal/commands/z/z.o"
	@echo "... internal/commands/z/z.i"
	@echo "... internal/commands/z/z.s"
	@echo "... internal/editor_status/editor_status.o"
	@echo "... internal/editor_status/editor_status.i"
	@echo "... internal/editor_status/editor_status.s"
	@echo "... internal/files/configs/helper/helper.o"
	@echo "... internal/files/configs/helper/helper.i"
	@echo "... internal/files/configs/helper/helper.s"
	@echo "... internal/files/configs/syntax_config/syntax_config.o"
	@echo "... internal/files/configs/syntax_config/syntax_config.i"
	@echo "... internal/files/configs/syntax_config/syntax_config.s"
	@echo "... internal/files/configs/theme_config/theme_config.o"
	@echo "... internal/files/configs/theme_config/theme_config.i"
	@echo "... internal/files/configs/theme_config/theme_config.s"
	@echo "... internal/files/exec/exec.o"
	@echo "... internal/files/exec/exec.i"
	@echo "... internal/files/exec/exec.s"
	@echo "... internal/files/helper/helper.o"
	@echo "... internal/files/helper/helper.i"
	@echo "... internal/files/helper/helper.s"
	@echo "... internal/files/log/log.o"
	@echo "... internal/files/log/log.i"
	@echo "... internal/files/log/log.s"
	@echo "... internal/helper/helper.o"
	@echo "... internal/helper/helper.i"
	@echo "... internal/helper/helper.s"
	@echo "... internal/highlighter/highlighter.o"
	@echo "... internal/highlighter/highlighter.i"
	@echo "... internal/highlighter/highlighter.s"
	@echo "... internal/history/history.o"
	@echo "... internal/history/history.i"
	@echo "... internal/history/history.s"
	@echo "... internal/keys/keys.o"
	@echo "... internal/keys/keys.i"
	@echo "... internal/keys/keys.s"
	@echo "... internal/loop/helper/helper.o"
	@echo "... internal/loop/helper/helper.i"
	@echo "... internal/loop/helper/helper.s"
	@echo "... internal/loop/initialisers/initialisers.o"
	@echo "... internal/loop/initialisers/initialisers.i"
	@echo "... internal/loop/initialisers/initialisers.s"
	@echo "... internal/loop/loop.o"
	@echo "... internal/loop/loop.i"
	@echo "... internal/loop/loop.s"
	@echo "... internal/loop/processors/processors.o"
	@echo "... internal/loop/processors/processors.i"
	@echo "... internal/loop/processors/processors.s"
	@echo "... internal/margin/margin.o"
	@echo "... internal/margin/margin.i"
	@echo "... internal/margin/margin.s"
	@echo "... internal/position/position.o"
	@echo "... internal/position/position.i"
	@echo "... internal/position/position.s"
	@echo "... internal/render/render.o"
	@echo "... internal/render/render.i"
	@echo "... internal/render/render.s"
	@echo "... internal/states/command/command.o"
	@echo "... internal/states/command/command.i"
	@echo "... internal/states/command/command.s"
	@echo "... internal/states/common/common.o"
	@echo "... internal/states/common/common.i"
	@echo "... internal/states/common/common.s"
	@echo "... internal/states/common/helper/helper.o"
	@echo "... internal/states/common/helper/helper.i"
	@echo "... internal/states/common/helper/helper.s"
	@echo "... internal/states/insert/insert.o"
	@echo "... internal/states/insert/insert.i"
	@echo "... internal/states/insert/insert.s"
	@echo "... internal/states/search/search.o"
	@echo "... internal/states/search/search.i"
	@echo "... internal/states/search/search.s"
	@echo "... internal/term_flags/term_flags.o"
	@echo "... internal/term_flags/term_flags.i"
	@echo "... internal/term_flags/term_flags.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

