# This is a basic workflow to help you get started with Actions

name: BuildTest

on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Clones master branch
        uses: actions/checkout@v2

      - name: Create build dir
        run: mkdir build
      - name: Build project
        run: |
          cd build
          cmake ..
          make
