# This is a basic workflow to help you get started with Actions

name: BuildTest

on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone master branch
        run: actions/checkout@v2
      - name: Create build dir
        run: mkdir build
      - name: Go to build dir
        run: cd build
      - name: Generate make file
        run: cmake ..
      - name: Build file
        run: make
